name: Release Charts

on:
  push:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'   

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: pages

      - name: Get index.yaml
        run: |
          cp ./index.yaml $HOME/index.yaml

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: release
